---
- name: IPtables | Get iptables rules
  command: iptables -L --wait
  register: iptablesrules
  always_run: yes

- name: IPtables | Open vxlan with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8472 -j ACCEPT -m comment --comment "nuage-vxlan"
  when: "'nuage-vxlan' not in iptablesrules.stdout"
  notify:
    - Save iptables rules
