apiVersion: v1
kind: Service
metadata: 
 name: nginx-deployment
 labels: 
   app: nginx
spec: 
 ports:
   # the port that this service should serve on
  -
   port: 80
   targetPort: 80
   protocol: "TCP"
 # label keys and values that must match in order to receive traffic for this service
 selector:
   app: nginx
