apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx
    nuage.io/subnet: demo
    nuage.io/zone: demo
    nuage.io/user: admin
spec:
  containers:
  - name: nginx-2
    image: rstarmer/nginx-curl
    ports:
    - containerPort: 80
