apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    nuage.io/subnet: demo
    nuage.io/zone: demo
    nuage.io/user: admin
    nuage.io/policy-group: demo
spec:
  containers:
  - name: nginx
    image: rstarmer/nginx-curl
    ports:
    - containerPort: 80
